# Generated by Django 6.0.3 on 2026-03-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('experiencia', models.IntegerField(default=0, help_text='Anos de experiência')),
                ('acamados', models.BooleanField(default=False)),
            ],
        ),
    ]
