# Generated by Django 6.0.3 on 2026-03-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
