# Generated by Django 6.0.3 on 2026-03-26 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0003_cuidador_bairro_cuidador_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
