# Generated by Django 6.0.3 on 2026-03-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0004_alter_cuidador_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='acamados',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='possui_mei',
        ),
        migrations.AddField(
            model_name='cuidador',
            name='atitude_crise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='capacitacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='cnae_correto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='disponibilidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='emissao_nf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='formacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='recusa_medicacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='registro_atividades',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='status_mei',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
