# Generated by Django 6.0.3 on 2026-03-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0005_remove_cuidador_acamados_remove_cuidador_experiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='atitude_crise',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='cnae_correto',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='emissao_nf',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='recusa_medicacao',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='registro_atividades',
        ),
        migrations.AddField(
            model_name='cuidador',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo Cadastro'), ('ENTREVISTA', 'Em Entrevista'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='NOVO', max_length=20),
        ),
    ]
