# Generated by Django 6.0.3 on 2026-03-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0006_remove_cuidador_atitude_crise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='disponibilidade',
        ),
        migrations.AddField(
            model_name='cuidador',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='lista_negra',
            field=models.BooleanField(default=False, verbose_name='Problemas Judiciais/Conduta'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='obs_lista_negra',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Bloqueio'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo Cadastro'), ('ENTREVISTA', 'Em Entrevista'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('BLACKLIST', 'LISTA NEGRA - BLOQUEADO')], default='NOVO', max_length=20),
        ),
    ]
