# Generated by Django 6.0.3 on 2026-03-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0007_remove_cuidador_disponibilidade_cuidador_curriculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='obs_lista_negra',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='status_mei',
        ),
        migrations.AddField(
            model_name='cuidador',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='obs_interna',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='lista_negra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='whatsapp',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
