# Generated by Django 6.0.3 on 2026-03-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuidadores', '0008_remove_cuidador_obs_lista_negra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidador',
            name='obs_interna',
        ),
    ]
